### ISSUE TITLE
ANSIBLE_CONFIG used incorrectly

### ISSUE THREAD

**Issue by clintonb** [roots/trellis#1216]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The `ANSIBLE_CONFIG` is supposed to be the path to a file (e.g., `<repo>/trellis/ansible.cfg`). Multiple locations in code treat the environment variable as if it is a directory path (e.g. `<repo>/trellis`). 

## Steps to reproduce

1. Follow the instructions to setup Trellis, or use an existing installation.
2. cd to the trellis directory.
3. Run the deploy script with the `ANSIBLE_CONFIG` set to `./ansible.cfg`: `ANSIBLE_CONFIG=./ansible.cfg bin/deploy.sh production example.com`

**Expected behavior:** Deploy should succeed

**Actual behavior:**
Deploy doesn't start.

```
ERROR! Unexpected Exception, this is probably a bug: No module named 'trellis'
the full traceback was:

Traceback (most recent call last):
  File "/Users/clintonb/workspace/mitcnc-wordpress-site/trellis/lib/trellis/plugins/callback/output.py", line 19, in <module>
    from trellis.utils import output as output
ModuleNotFoundError: No module named 'trellis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/lib/python3.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 99, in run
    self._tqm.load_callbacks()
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 134, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/lib/python3.7/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/Users/clintonb/.virtualenvs/mitcnc-wordpress-site/lib/python3.7/site-packages/ansible/plugins/loader.py", line 525, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/clintonb/workspace/mitcnc-wordpress-site/trellis/lib/trellis/plugins/callback/output.py", line 24, in <module>
    from trellis.utils import output as output
ModuleNotFoundError: No module named 'trellis'
```

**Reproduces how often:** Always

## Versions
1.5.0: August 5th, 2020 on the `python:3.7` Docker image and macOS

**Comment by swalkinshaw** [comment]
Slightly confused why this didn't cause more problems for Vagrant since the env var was actually set within Ruby. Anyway, thanks for reporting and the fix.
