### ISSUE TITLE
Error on the “Install the Ansible Galaxy roles” step of Trellis installation 

### ISSUE THREAD

**Issue by fredcerdeira** [roots/trellis#575]
## Submit a feature request or bug report

- [x] This is a bug report
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

**What is the current behavior?**

When Running: $ ansible-galaxy install -r requirements.yml

ERROR! Unexpected Exception: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=11.3'))
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 73, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/Library/Python/2.7/site-packages/ansible/cli/galaxy.py", line 38, in <module>
    from ansible.galaxy.role import GalaxyRole
  File "/Library/Python/2.7/site-packages/ansible/galaxy/role.py", line 35, in <module>
    from ansible.playbook.role.requirement import RoleRequirement
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/Library/Python/2.7/site-packages/ansible/playbook/base.py", line 35, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 32, in <module>
    from ansible.parsing.vault import VaultLib
  File "/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
    from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
    from cryptography.hazmat.backends.interfaces import HashBackend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=11.3'))

**What is the expected or desired behavior?**

Install Ansible roles with no problems

---

## Bug report

**Please provide steps to reproduce, including full log output:**

$ansible-galaxy install -r requirements.yml

**Please describe your local environment:**

Ansible version:  2.0.2.0

OS: X  10.11.4 (El Capitain)

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

Development

**Comment by swalkinshaw** [comment]
I responded on your Discourse thread: https://discourse.roots.io/t/error-on-the-install-the-ansible-galaxy-roles-step-of-trellis-installation-newbie/6611/3

This is not a Trellis issue.

**Comment by fredcerdeira** [comment]
Thanks for your support!
