### ISSUE TITLE
Updating OS to Sierra results in build failing due to OpenSSL 0.9.8 being outdated

### ISSUE THREAD

**Issue by Buretta** [roots/trellis#669]
## Submit a feature request or bug report
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.
---

**What is the current behavior?**

Vagrant up will fail and results in the following error
`You are linking against OpenSSL 0.9.8, which is no longer supported`

**What is the expected or desired behavior?**

I should be able to update OpenSSL with Homebrew but Trellis continues to use the system OS version which results in the failed provision.
---
## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Running on OS Sierra 10.12 (16A323)
Require SSL on build
Encrypt group_vars with vault
Vagrant Up
Error, debug output below

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/Library/Python/2.7/site-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 85, in __init__
    self.parse_inventory(host_list)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 144, in parse_inventory
    group.vars = combine_vars(group.vars, self.get_group_variables(group.name))
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 509, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 527, in _get_group_variables
    vars = combine_vars(vars, self.get_group_vars(group))
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 707, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 746, in _get_hostgroup_vars
    results = combine_vars(results, self._variable_manager.add_group_vars_file(base_path, self._loader))
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 578, in add_group_vars_file
    (name, data) = self._load_inventory_file(path, loader)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 535, in _load_inventory_file
    _found, results = self._load_inventory_file(path=p, loader=loader)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 550, in _load_inventory_file
    data = loader.load_from_file(path)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 113, in load_from_file
    (file_data, show_content) = self._get_file_contents(file_name)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 172, in _get_file_contents
    data = self._vault.decrypt(data)
  File "/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py", line 169, in decrypt
    b_data = this_cipher.decrypt(b_data, self.b_password)
  File "/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py", line 679, in decrypt
    key1, key2, iv = self.gen_key_initctr(password, salt)
  File "/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py", line 621, in gen_key_initctr
    backend = default_backend()
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/Users/bduzita/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 47, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 250, in <module>
    _verify_openssl_version(Binding.lib.SSLeay())
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 230, in _verify_openssl_version
    "You are linking against OpenSSL 0.9.8, which is no longer "
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
```

**Please describe your local environment:**

Ansible version:  2.1.0.0

OS: Sierra 10.12 (16A323)

Vagrant version: 1.8.6

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/you-are-linking-against-openssl-0-9-8-which-is-no-longer-supported/7796

**Comment by swalkinshaw** [comment]
There's nothing Trellis can do about this unfortunately. It's an issue with Homebrew (I guess?).

See http://stackoverflow.com/questions/38670295/brew-refusing-to-link-openssl and http://stackoverflow.com/questions/37690054/python-and-openssl-version-reference-issue-on-os-x for potential solutions.
