### ISSUE TITLE
Permission denied, deploy task refuses to create website directory.

### ISSUE THREAD

**Issue by nextgenthemes** [roots/trellis#908]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse]

Please let me know if there is sensible information in here I should not share. My URL and server IP not needs to be secret, changed user and servername.

This may relate to #668 I am not sure.

```
ansible-playbook deploy.yml -e "site=nico.onl env=production" -vvv

[...]

TASK [deploy : Initialize] **********************************************************************************************************************************************************************************
task path: /home/user23/websites/trellis/roles/deploy/tasks/initialize.yml:8
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/web_infrastructure/deploy_helper.py
<45.55.72.81> ESTABLISH SSH CONNECTION FOR USER: web
<45.55.72.81> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=web -o ConnectTimeout=10 -o ControlPath=/home/user23/.ansible/cp/1048c4ec9a 45.55.72.81 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<45.55.72.81> (1, '', 'Traceback (most recent call last):\n  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 529, in <module>\n    main()\n  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 490, in main\n    changes += deploy_helper.create_path(facts[\'project_path\'])\n  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 352, in create_path\n    os.makedirs(path)\n  File "/usr/lib/python2.7/os.py", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: \'/srv/www/nico.onl\'\n')
System info:
  Ansible 2.4.1.0; Linux
  Trellis at "Normalize `apt` tasks"
---------------------------------------------------
MODULE FAILURE
Traceback (most recent call last):
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 529, in
<module>
    main()
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 490, in
main
    changes += deploy_helper.create_path(facts['project_path'])
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 352, in
create_path
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/www/nico.onl'

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 529, in <module>
    main()
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 490, in main
    changes += deploy_helper.create_path(facts['project_path'])
  File "/tmp/ansible_bUirSg/ansible_module_deploy_helper.py", line 352, in create_path
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/www/nico.onl'

fatal: [45.55.72.81]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stdout": "", 
    "rc": 1
}
	to retry, use: --limit @/home/.../deploy.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
45.55.72.81                : ok=2    changed=0    unreachable=0    failed=1   
localhost                  : ok=0    changed=0    unreachable=0    failed=0
```

I had something setup wrong b4 I think this may be how I got here. I have trellis setup to block root ssh and it has the pass do get sudo with the admin user i can use myself so ssh in. I see this in `/srv/www`. In the letsencrypt dir there is only a empty `ping.txt`. Should Trellis not get sudo at this point and set the permissions right? Should I set them manually now? To what exactly? My guess is the root:root is wrong here but I think Trellis should automatically take care of this.

```
user@vps:/srv/www$ ll -a
total 12
drwxr-xr-x 3 root root 4096 Oct 27 03:24 ./
drwxr-xr-x 3 root root 4096 Oct 27 03:24 ../
drwxr-xr-x 2 root root 4096 Oct 27 03:25 letsencrypt/
```

**Comment by greatislander** [comment]
It looks like you have not run `ansible-playbook server.yml -e env=production`. You can't deploy if you haven't provisioned the server. See: https://roots.io/trellis/docs/remote-server-setup/

**Comment by nextgenthemes** [comment]
Oh well thanks, I thought I already did that.
